{ pkgs, ... }: {
  environment.systemPackages = [
    pkgs.nixos-option
    pkgs.fd
    pkgs.tailscale
    pkgs.killall
    pkgs.ripgrep
    pkgs.tealdeer
    pkgs.direnv
    pkgs.nodePackages.yaml-language-server
    pkgs.git
    pkgs.git-lfs
    pkgs.sqlite
    pkgs.julia_16-bin
    pkgs.graphviz
    pkgs.github-cli
    pkgs.virt-manager
    pkgs.gnumake
    pkgs.cmake
    pkgs.gnuplot
    pkgs.editorconfig-core-c
    pkgs.jq
    pkgs.jre
    pkgs.nixfmt
    pkgs.nix-linter
    pkgs.zip
    pkgs.unzip
    pkgs.rclone
    pkgs.wget
    pkgs.curl
    pkgs.scilab-bin
  ];
  imports = [
    ./dev/python.nix
    ./dev/r.nix
    ./dev/csharp.nix
    ./dev/clang.nix
    ./dev/go.nix
  ];
}
