{ config, pkgs, ... }:
let
  my-python-packages = python-packages: with python-packages; [ grip ];
  python-with-my-packages = pkgs.python3.withPackages my-python-packages;
in {
  home.packages = [
    pkgs.nixos-option
    pkgs.libreoffice-fresh
    pkgs.xkcd-font
    pkgs.gammastep
    pkgs.texlive.combined.scheme-full
    pkgs.networkmanagerapplet
    pkgs.htop
    pkgs.gimp
    pkgs.picom
    pkgs.fd
    pkgs.nerdfonts
    pkgs.tailscale
    pkgs.multimc
    pkgs.killall
    pkgs.arandr
    pkgs.xorg.xwininfo
    pkgs.ripgrep
    pkgs.xclip
    pkgs.xwallpaper
    pkgs.brillo
    pkgs.lxappearance
    pkgs.numlockx
    pkgs.blueman
    pkgs.tealdeer
    pkgs.direnv
    pkgs.pinentry-qt
    pkgs.nodePackages.yaml-language-server
    pkgs.ocrmypdf
    pkgs.multilockscreen
    pkgs.yadm
    pkgs.pcmanfm
    pkgs.pandoc
    pkgs.aspell
    pkgs.aspellDicts.pl
    pkgs.aspellDicts.en
    pkgs.ispell
    pkgs.languagetool
    pkgs.libreoffice
    pkgs.hugo
    pkgs.thunderbird-bin-91
    pkgs.birdtray
    pkgs.teams
    pkgs.slack
    pkgs.kotatogram-desktop
    pkgs.git
    pkgs.git-lfs
    pkgs.sqlite
    pkgs.julia_16-bin
    python-with-my-packages
    pkgs.R
    pkgs.graphviz
    pkgs.github-cli
    pkgs.virt-manager
    pkgs.gnumake
    pkgs.cmake
    pkgs.gnuplot
    pkgs.editorconfig-core-c
    pkgs.pyright
    pkgs.black
    pkgs.jq
    pkgs.jre
    pkgs.maim
    pkgs.nixfmt
    pkgs.go
    pkgs.megasync
    pkgs.zip
    pkgs.unzip
    pkgs.rclone
    pkgs.pavucontrol
    pkgs.pamixer
    pkgs.youtube-dl
    pkgs.alsa-utils
    pkgs.freetube
    pkgs.calibre
    pkgs.spotify
    pkgs.spicetify-cli
    pkgs.wget
    pkgs.curl
    pkgs.firefox
    pkgs.brave
    pkgs.spectacle
  ];
}
